spring:
  datasource:
    #数据库基本配置
    username: root
    password: zhuyuf
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.95.212.214:3306/gkwb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    #filters: stat,wall,log4j
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zyf.springboot06datamybatis.bean


server:
  port: 80
  servlet:
    context-path: /gkwb
logging:
  level:
    com.zyf.springboot06datamybatis: debug